[project]
name = "unit-convertor"
version = "0.1.0"
description = "Unit converter for Length, Weight, Temperature & Time"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = []

[tool.poetry]
package-mode = false
